### ISSUE TITLE
Use symbolic names for array sizes in generated documentation

### ISSUE THREAD

**Issue by jnikula** [jnikula/hawkmoth#174]
Given:

```
/** size */
#define SIZE 5

/** array */
int array[SIZE];

```
it would be nice if the generated documentation actually had `int array[SIZE];` instead of the current `int array[5];`

**Comment by BrunoMSantos** [comment]
So, this immediately made me think of #92. Seems like a similar problem asking for a general solution. Same for the enumerator initializers which I just mentioned in #176 and just about any other pre-processor symbol we might not want to expand. Thoughts?

**Comment by jnikula** [comment]
> So, this immediately made me think of #92. Seems like a similar problem asking for a general solution. Same for the enumerator initializers which I just mentioned in #176 and just about any other pre-processor symbol we might not want to expand. Thoughts?

Do you basically mean #135 enhanced with passing the Cursor to the event handler?

For the most part I really just want sane defaults. But beyond that, perhaps the right thing is to give the user the tools to go wild, instead of developing complex configuration options. I don't know. It also seems scary to give the user access to the Cursor, as it creates a dependency on Clang details which we can't hide from the user.

I just merged #176 as the sane default thing to do. But it's prints the numeric value, not the symbolic thing in source.

**Comment by BrunoMSantos** [comment]
> > So, this immediately made me think of #92. Seems like a similar problem asking for a general solution. Same for the enumerator initializers which I just mentioned in #176 and just about any other pre-processor symbol we might not want to expand. Thoughts?
> 
> Do you basically mean #135 enhanced with passing the Cursor to the event handler?

Yeah, I think we've discussed it in the past in fact. Though I'm not sure it should be the 'clang' cursor instead of a documentation centric abstraction of the cursor that allows for easier manipulation by the user. E.g. with methods to extract qualifiers or whatever hiding away all the AST's oddities. But those are details I think.

> For the most part I really just want sane defaults. But beyond that, perhaps the right thing is to give the user the tools to go wild, instead of developing complex configuration options.

Yup, I think the extension is a nice compromise. Whether replacing `_Bool` is the 'right' default or not I'm not so sure. I can think of other cases where it would make about as much sense (e.g. `#define memcpy __builtin_memcpy`) and yet I would prefer it to be expanded by default I think. Consistency and so on...

> I don't know. It also seems scary to give the user access to the Cursor, as it creates a dependency on Clang details which we can't hide from the user.

Solved by creating our own cursor object I think. I've played around with this before by the way, but there were a couple of things that were not so trivial to refactor.

> I just merged #176 as the sane default thing to do. But it's prints the numeric value, not the symbolic thing in source.

:+1:

**Comment by jnikula** [comment]
Implemented in #186.
