### ISSUE TITLE
Wrong rendering when defining array

### ISSUE THREAD

**Issue by LudovicGuerra** [jnikula/hawkmoth#22]
I have a problem when I try to document array. This is what I define:

```
#define DRV_RTC_NBDEVS 1
/**
 * This variable translate the app device id to the physical one
 */
static int_t _app_device_id_to_physical_device_id[DRV_RTC_NBDEVS] =
{
  0,
};
```

And this is what I got. The type int_t not recognize, I have the [1]. I lose the static but maybe it is intentional ?

![image](https://user-images.githubusercontent.com/19329243/85707183-3c140d80-b6e3-11ea-91bc-0e123bf381a0.png)

**Comment by BrunoMSantos** [comment]
`int_t` not being recognized is probably due to Clang missing some include paths. This is the subject of issue #13, but otherwise possible to work around it.

The automatic replacement of `[DRV_RTC_NBDEVS]` for `[1]` is also a result of how Clang parses it. Not sure we can do much here: note that simply preventing the precompiler to kick in also prevents `#ifdef`s from being resolved. Oh, and there's also issue #17 about the weird positioning of the `[1]`. 

Finally, the `static` is not part of the type, which is why it's not shown. To keep it we'd need to stich it back in there, which is probably not a bad idea. However, the same goes for `__attribute__`, `extern`, `inline`, prefix macros, etc. And while `static` can be checked through `cursor.storage_class`, the other cases could only be met by bypassing most of Clang and go with `.get_tokens()` I think. Is `static` the only case affecting you?

**Comment by LudovicGuerra** [comment]
Thanks for your help.

1) Ok I take note and will look when I come back to sphinx doc (we gave up on sphinx doc as there was too many problem with hawkmoth for the time beeing)

2) Hum I'll check, do you know how to not use the precompiler ? Parameter to give to clang ?

3) Static is the most obvious case because we have it everywhere.
We also have others as extern or inline, but it either didn't show up in my specific code where I tested sphinx or it got lost  in all the error we had. But having all those keyword would obviously be nice, but I understand the difficulty.

**Comment by BrunoMSantos** [comment]
Hmm, I'm not sure that would help us even if there was a way, I was trying to give some context. Ultimately, even that simple snippet of code is not exactly valid C without the preprocessor pass and Clang would trip up on it.

With that said, the information is not entirely lost, it's just not as readily available, much like the point about `inline`s, etc. And I'm not sure the parser is in a state where it can accommodate such a big increase in complexity yet.

**Comment by jnikula** [comment]
You'd need to have the `#include` (or `typedef`) in place to define `int_t`. The type is unknown to clang, so it'll be unknown to hawkmoth.

At least for the time being I'm resisting the urge to add a multitude of extra attributes such as storage class in the documentation, in the interest of keeping it simple.
