### ISSUE TITLE
Building on readthedocs

### ISSUE THREAD

**Issue by f0uriest** [jnikula/hawkmoth#25]
I'm having trouble getting hawkmoth to work when building on RTD due to it not finding libclang.so
Do you know of any standard workarounds?

**Comment by BrunoMSantos** [comment]
Hi f0uriest. As far as I'm aware they don't provide clang nor any of other common tools as they only care about sphinx documentation and not allowing a full fledged compilation server or CI. You could always reach them though, who knows?

As for workarounds:

These days you can often use GitLab's CI and 'pages' to get the same effect in an independent way. There's probably something equivalent for GitHub too and note that the RTD theme is easily available as a Python package. I actually much prefer this anyway and I'm planning on doing that for Hawkmoth at some point so that we can run the tests on CI as well, etc.

And then there's how hawkmoth currently [handles it](https://raw.githubusercontent.com/jnikula/hawkmoth/master/doc/examples.rst): it has a script that generates static .rst that is then committed as part of the repo and the build falls back to it if it cannot find clang.

**Comment by jnikula** [comment]
RTD does not support installing clang or having custom containers with clang for building the documentation. It seems to be a decision they've made and are sticking with it. Unfortunately this means you can't use Hawkmoth on RTD.

As said above, we use statically generated rst for Hawkmoth documentation on RTD. It works, because we have the pre-generated rst available due to all the examples being also part of the test suite. It might be cumbersome for regular projects. It's probably better to find an alternative service for building and hosting the documentation, with custom containers.

**Comment by jnikula** [comment]
@f0uriest We now have a way to use Hawkmoth on Read the Docs: https://hawkmoth.readthedocs.io/en/latest/installation.html#read-the-docs
