### ISSUE TITLE
Function parameter direction

### ISSUE THREAD

**Issue by 6r1d** [jnikula/hawkmoth#32]
Hello. I have started using Hawkmoth today and noticed a [little difference with Doxygen](https://www.doxygen.nl/manual/docblocks.html).

As the title states, having Doxygen-like [parameter direction](https://stackoverflow.com/questions/47732665/): `[in]`, `[out]`, `[in,out]` would be very nice.

I wonder if it is an appropriate change (hopefully it is).

**Comment by BrunoMSantos** [comment]
Hi!
Hmm, parsing that information wouldn't be too hard, but parameter direction is not supported in sphinx so we'd have no (standard) way of registering it. Not sure we can do a lot here :/

Note that Doxygen syntax is only superficially supported at best and will likely remain so indefinitely, in great part for technical reasons.

**Comment by jnikula** [comment]
I've got good news and bad news.

Bad news first. Improving transformations for Doxygen-like input is really not a priority for me. It basically means implementing a parser converting from Doxygen to reStructuredText, and I'd rather focus on the Clang and Sphinx parts, with documentation written in pure reStructuredText. The current transformations are just a series of simple regular expression pattern replacements.

But wait, there's good news. I've got a bunch of code already abstracting the current Doxygen parsing to generic transformations on the comments. While I don't personally want to put effort into the Doxygen parsing, I acknowledge the need to handle existing documentation comments when considering a switch to Hawkmoth. With the transformations, you could write your own conversions for the things you need, in a plugin-like manner. With Sphinx lacking a standard way of documenting parameter direction, you could choose how you want it expressed instead of Hawkmoth making the decision for you.

**Comment by jnikula** [comment]
Also, you could use the transformations with things like [napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html). Hawkmoth would provide a mechanism to go wild with the syntax you want to use, but would get out of the way and not limit you with any hardcoded policy.

I'm hoping to get this done for the next release, within maybe a month.

**Comment by BrunoMSantos** [comment]
Hmm, here I thought that was already possible and that napoleon would kick in later in the whole pipeline and work fine already... A quick test seems to show otherwise. Honestly I always took the core interface to sphinx for granted :sweat_smile: 

That should be interesting then!

**Comment by jnikula** [comment]
@6r1d I merged #50 and released v0.8.0 and came back here to close this one, re-read everything, and started wondering if I completely misunderstood your original issue. I thought you meant the compatibility support for Doxygen, i.e. converting `@param[in]` etc. in to suitable formats. But perhaps you were actually talking about supporting directoin in plain reStructuredText?

**Comment by 6r1d** [comment]
> and started wondering if I completely misunderstood your original issue

Thanks for reminding me. Personally, any way to point out if some function argument is used to point to input, output or both works. :-)

It doesn't need to be compatible with Doxygen, I was just playing with code commented in Doxygen style and found it useful, at the very least because I can avoid losing details while "translating" Doxygen documentation.

> But perhaps you were actually talking about supporting direction in plain reStructuredText?

How would that look like? I mean, I can just write the direction in bold font or as a text already.

**Comment by jnikula** [comment]
I think the answer is, Sphinx does not support this as a dedicated mechanism, and I don't think we want to add special handling for it either. However, here's my recommended workaround.

Add reStructuredText replacement directives, for example:

```
.. |in| replace:: ⇒
.. |out| replace:: ⇐
.. |in,out| replace:: ⇔
```

Here, I've added Unicode arrows, but you can experiment and choose what you like. You could just add them as text with emphasis too, for example:

```
.. |in| replace:: **[in]**
.. |out| replace:: **[out]**
.. |in,out| replace:: **[in,out]**
```

Then you'd document the parameters as:

```
:param foo: |in| Parameter foo description
:param bar: |out| Parameter bar description
:param baz: |in,out| Parameter baz description
```

The key here is to use the |replacement| syntax, so you get syntax checking for them, and you can experiment and replace the output in a single point of truth.

Hope this helps.
